# Generated by Django 5.1.4 on 2024-12-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_group_room_schedule_group_schedule_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
